import mysql.connector as my
con=my.connect(host='localhost',user='root',passwd='1234')
cur=con.cursor()
cur.execute('create database if not exists proj')
cur.execute('use proj')
cur.execute('create table if not exists menu(itemid int primary key,itemname char(25),price int,variety char(15),v_nv char(3))')


# 1) SWEETS (variety = 'sweet')
cur.execute("INSERT INTO menu VALUES(1,'rava kesari',75,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(2,'carrot halwa',65,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(3,'bread halwa',70,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(4,'mysore pak (3pcs)',70,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(5,'badhushah (3pcs)',65,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(6,'gulab jamun (2pcs)',40,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(7,'rasgulla (2pcs)',45,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(8,'jalebi (4pcs)',35,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(9,'badam halwa',80,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(10,'pineapple kesari',70,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(11,'milk peda',30,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(12,'kaju katli',85,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(13,'dry fruit barfi',90,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(14,'maalpua',55,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(15,'chum chum',50,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(16,'sandesh',55,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(17,'coconut laddu',45,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(18,'rabdi',80,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(19,'basundi',75,'sweet','v')")
cur.execute("INSERT INTO menu VALUES(20,'boondi laddu',35,'sweet','v')")


# 2) SOUPS (variety = 'soup')
cur.execute("INSERT INTO menu VALUES(21,'tomato soup',120,'soup','v')")
cur.execute("INSERT INTO menu VALUES(22,'sweet corn soup',100,'soup','v')")
cur.execute("INSERT INTO menu VALUES(23,'mushroom soup',85,'soup','v')")
cur.execute("INSERT INTO menu VALUES(24,'hot and pepper soup',100,'soup','v')")
cur.execute("INSERT INTO menu VALUES(25,'veg clear soup',90,'soup','v')")
cur.execute("INSERT INTO menu VALUES(26,'spinach soup',95,'soup','v')")
cur.execute("INSERT INTO menu VALUES(27,'cream of broccoli soup',110,'soup','v')")
cur.execute("INSERT INTO menu VALUES(28,'manchow veg soup',115,'soup','v')")
cur.execute("INSERT INTO menu VALUES(29,'thai coconut soup',130,'soup','v')")
cur.execute("INSERT INTO menu VALUES(30,'french onion soup',125,'soup','nv')")
cur.execute("INSERT INTO menu VALUES(31,'garlic chicken soup',120,'soup','nv')")
cur.execute("INSERT INTO menu VALUES(32,'hot & sour chicken soup',130,'soup','nv')")
cur.execute("INSERT INTO menu VALUES(33,'prawn clear soup',135,'soup','nv')")
cur.execute("INSERT INTO menu VALUES(34,'mutton pepper soup',120,'soup','nv')")
cur.execute("INSERT INTO menu VALUES(35,'crab soup',140,'soup','nv')")
cur.execute("INSERT INTO menu VALUES(36,'seafood chowder',150,'soup','nv')")
cur.execute("INSERT INTO menu VALUES(37,'egg drop soup',110,'soup','nv')")
cur.execute("INSERT INTO menu VALUES(38,'cream chicken soup',130,'soup','nv')")
cur.execute("INSERT INTO menu VALUES(39,'butter corn chick soup',135,'soup','nv')")
cur.execute("INSERT INTO menu VALUES(40,'tom yum prawn soup',150,'soup','nv')")


# 3) STARTERS (variety = 'starter')
cur.execute("INSERT INTO menu VALUES(41,'gobi 65',120,'starter','v')")
cur.execute("INSERT INTO menu VALUES(42,'paneer tikka',130,'starter','v')")
cur.execute("INSERT INTO menu VALUES(43,'mushroom tikka',135,'starter','v')")
cur.execute("INSERT INTO menu VALUES(44,'veg manchurian dry',125,'starter','v')")
cur.execute("INSERT INTO menu VALUES(45,'crispy corn',115,'starter','v')")
cur.execute("INSERT INTO menu VALUES(46,'honey chilli potato',120,'starter','v')")
cur.execute("INSERT INTO menu VALUES(47,'paneer 65',130,'starter','v')")
cur.execute("INSERT INTO menu VALUES(48,'babycorn golden fry',120,'starter','v')")
cur.execute("INSERT INTO menu VALUES(49,'veg spring rolls',110,'starter','v')")
cur.execute("INSERT INTO menu VALUES(50,'cheese balls',130,'starter','v')")
cur.execute("INSERT INTO menu VALUES(51,'chicken 65',145,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(52,'chicken 88',150,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(53,'chicken 007',140,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(54,'chicken tikka',145,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(55,'chicken tandoori',170,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(56,'honey chicken',135,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(57,'dragon chicken',165,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(58,'pepper chicken',160,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(59,'crab lollipop',175,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(60,'fish fingers',160,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(61,'golden prawn fry',170,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(62,'roasted fish',165,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(63,'fish 65',155,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(64,'grill chicken full',260,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(65,'grill chicken half',150,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(66,'tandoori prawn',190,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(67,'chicken lollipop',140,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(68,'malai tikka',155,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(69,'mutton seekh kebab',190,'starter','nv')")
cur.execute("INSERT INTO menu VALUES(70,'fish tikka',180,'starter','nv')")


# 4) SOUTH INDIAN MAINS (variety = 'maindish')
cur.execute("INSERT INTO menu VALUES(71,'plain dosa',45,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(72,'idli (2 pcs)',30,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(73,'ghee roast',55,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(74,'masala dosa',60,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(75,'podi dosa',55,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(76,'mushroom dosa',65,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(77,'paneer dosa',70,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(78,'onion dosa',55,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(79,'upma',40,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(80,'idiyappam',50,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(81,'pongal',55,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(82,'rava dosa',55,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(83,'onion uthappam',60,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(84,'mixed veg uthappam',65,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(85,'cheese dosa',75,'maindish','v')")
cur.execute("INSERT INTO menu VALUES(86,'egg dosa',65,'maindish','nv')")
cur.execute("INSERT INTO menu VALUES(87,'chicken dosa',70,'maindish','nv')")
cur.execute("INSERT INTO menu VALUES(88,'mutton dosa',85,'maindish','nv')")
cur.execute("INSERT INTO menu VALUES(89,'kheema dosa',90,'maindish','nv')")
cur.execute("INSERT INTO menu VALUES(90,'paneer uthappam',70,'maindish','v')")


# 5) ROTIS (variety = 'roti')
cur.execute("INSERT INTO menu VALUES(91,'phulka',35,'roti','v')")
cur.execute("INSERT INTO menu VALUES(92,'chappati',25,'roti','v')")
cur.execute("INSERT INTO menu VALUES(93,'naan',30,'roti','v')")
cur.execute("INSERT INTO menu VALUES(94,'butter naan',40,'roti','v')")
cur.execute("INSERT INTO menu VALUES(95,'garlic naan',45,'roti','v')")
cur.execute("INSERT INTO menu VALUES(96,'cheese naan',55,'roti','v')")
cur.execute("INSERT INTO menu VALUES(97,'paratha',20,'roti','v')")
cur.execute("INSERT INTO menu VALUES(98,'aloo paratha',45,'roti','v')")
cur.execute("INSERT INTO menu VALUES(99,'tandoori roti',30,'roti','v')")
cur.execute("INSERT INTO menu VALUES(100,'rumali roti',30,'roti','v')")


# 6) GRAVIES (variety = 'gravy')
cur.execute("INSERT INTO menu VALUES(101,'paneer butter masala',165,'gravy','v')")
cur.execute("INSERT INTO menu VALUES(102,'mushroom gravy',150,'gravy','v')")
cur.execute("INSERT INTO menu VALUES(103,'babycorn gravy',145,'gravy','v')")
cur.execute("INSERT INTO menu VALUES(104,'malai kofta',170,'gravy','v')")
cur.execute("INSERT INTO menu VALUES(105,'kadai paneer',160,'gravy','v')")
cur.execute("INSERT INTO menu VALUES(106,'palak paneer',155,'gravy','v')")
cur.execute("INSERT INTO menu VALUES(107,'mixed veg curry',140,'gravy','v')")
cur.execute("INSERT INTO menu VALUES(108,'dal makhani',145,'gravy','v')")
cur.execute("INSERT INTO menu VALUES(109,'butter chicken',180,'gravy','nv')")
cur.execute("INSERT INTO menu VALUES(110,'chettinad chicken',190,'gravy','nv')")
cur.execute("INSERT INTO menu VALUES(111,'kadai chicken',175,'gravy','nv')")
cur.execute("INSERT INTO menu VALUES(112,'egg curry',140,'gravy','nv')")
cur.execute("INSERT INTO menu VALUES(113,'fish curry',160,'gravy','nv')")
cur.execute("INSERT INTO menu VALUES(114,'prawn masala',185,'gravy','nv')")
cur.execute("INSERT INTO menu VALUES(115,'mutton curry',200,'gravy','nv')")


# 7) RICE ITEMS (variety = 'rice')
cur.execute("INSERT INTO menu VALUES(116,'curd rice',45,'rice','v')")
cur.execute("INSERT INTO menu VALUES(117,'sambar rice',55,'rice','v')")
cur.execute("INSERT INTO menu VALUES(118,'dal rice',50,'rice','v')")
cur.execute("INSERT INTO menu VALUES(119,'rasam rice',45,'rice','v')")
cur.execute("INSERT INTO menu VALUES(120,'podi rice',55,'rice','v')")
cur.execute("INSERT INTO menu VALUES(121,'lemon rice',55,'rice','v')")
cur.execute("INSERT INTO menu VALUES(122,'tamarind rice',60,'rice','v')")
cur.execute("INSERT INTO menu VALUES(123,'tomato rice',60,'rice','v')")
cur.execute("INSERT INTO menu VALUES(124,'veg pulao',110,'rice','v')")
cur.execute("INSERT INTO menu VALUES(125,'plain fried rice',100,'rice','v')")
cur.execute("INSERT INTO menu VALUES(126,'veg fried rice',110,'rice','v')")
cur.execute("INSERT INTO menu VALUES(127,'paneer fried rice',125,'rice','v')")
cur.execute("INSERT INTO menu VALUES(128,'mushroom fried rice',130,'rice','v')")
cur.execute("INSERT INTO menu VALUES(129,'schezwan veg rice',130,'rice','v')")
cur.execute("INSERT INTO menu VALUES(130,'chicken gravy rice',145,'rice','nv')")
cur.execute("INSERT INTO menu VALUES(131,'mutton gravy rice',165,'rice','nv')")
cur.execute("INSERT INTO menu VALUES(132,'prawn thokku rice',155,'rice','nv')")
cur.execute("INSERT INTO menu VALUES(133,'fish gravy rice',145,'rice','nv')")
cur.execute("INSERT INTO menu VALUES(134,'chicken fried rice',150,'rice','nv')")
cur.execute("INSERT INTO menu VALUES(135,'egg fried rice',135,'rice','nv')")
cur.execute("INSERT INTO menu VALUES(136,'schezwan chicken rice',170,'rice','nv')")
cur.execute("INSERT INTO menu VALUES(137,'prawn fried rice',180,'rice','nv')")
cur.execute("INSERT INTO menu VALUES(138,'mutton fried rice',190,'rice','nv')")


# 8) BIRIYANIS (variety = 'biriyani')
cur.execute("INSERT INTO menu VALUES(139,'paneer biriyani',185,'biriyani','v')")
cur.execute("INSERT INTO menu VALUES(140,'mushroom biriyani',170,'biriyani','v')")
cur.execute("INSERT INTO menu VALUES(141,'veg dum biriyani',165,'biriyani','v')")
cur.execute("INSERT INTO menu VALUES(142,'plain biriyani',150,'biriyani','v')")
cur.execute("INSERT INTO menu VALUES(143,'egg biriyani',160,'biriyani','nv')")
cur.execute("INSERT INTO menu VALUES(144,'chicken biriyani',180,'biriyani','nv')")
cur.execute("INSERT INTO menu VALUES(145,'mutton biriyani',210,'biriyani','nv')")
cur.execute("INSERT INTO menu VALUES(146,'prawn biriyani',190,'biriyani','nv')")
cur.execute("INSERT INTO menu VALUES(147,'fish biriyani',185,'biriyani','nv')")
cur.execute("INSERT INTO menu VALUES(148,'chettinad chick biriyani',200,'biriyani','nv')")
cur.execute("INSERT INTO menu VALUES(149,'hyd veg biriyani',175,'biriyani','v')")
cur.execute("INSERT INTO menu VALUES(150,'hyd chicken biriyani',205,'biriyani','nv')")


# 9) DESSERTS (variety = 'desert')
cur.execute("INSERT INTO menu VALUES(151,'butterscotch scoop',60,'desert','v')")
cur.execute("INSERT INTO menu VALUES(152,'chocolate scoop',55,'desert','v')")
cur.execute("INSERT INTO menu VALUES(153,'vanilla scoop',50,'desert','v')")
cur.execute("INSERT INTO menu VALUES(154,'strawberry scoop',55,'desert','v')")
cur.execute("INSERT INTO menu VALUES(155,'blackcurrant scoop',60,'desert','v')")
cur.execute("INSERT INTO menu VALUES(156,'mango scoop',60,'desert','v')")
cur.execute("INSERT INTO menu VALUES(157,'kulfi stick',50,'desert','v')")
cur.execute("INSERT INTO menu VALUES(158,'malai kulfi',65,'desert','v')")
cur.execute("INSERT INTO menu VALUES(159,'sitaphal kulfi',70,'desert','v')")
cur.execute("INSERT INTO menu VALUES(160,'fruit salad',70,'desert','v')")
cur.execute("INSERT INTO menu VALUES(161,'fruit salad icecream',90,'desert','v')")
cur.execute("INSERT INTO menu VALUES(162,'brownie',80,'desert','v')")
cur.execute("INSERT INTO menu VALUES(163,'brownie with icecream',120,'desert','v')")
cur.execute("INSERT INTO menu VALUES(164,'choco lava cake',110,'desert','v')")
cur.execute("INSERT INTO menu VALUES(165,'sizzling brownie',130,'desert','v')")
cur.execute("INSERT INTO menu VALUES(166,'double ka meetha',80,'desert','v')")
cur.execute("INSERT INTO menu VALUES(167,'phirni',75,'desert','v')")
cur.execute("INSERT INTO menu VALUES(168,'rasmalai (2pcs)',90,'desert','v')")
cur.execute("INSERT INTO menu VALUES(169,'oreo sundae',120,'desert','v')")
cur.execute("INSERT INTO menu VALUES(170,'falooda royale',130,'desert','v')")


# 10) HOT BEVERAGES (variety = 'hotbeverage')
cur.execute("INSERT INTO menu VALUES(171,'filter coffee',35,'hotbeverage','v')")
cur.execute("INSERT INTO menu VALUES(172,'degree coffee',40,'hotbeverage','v')")
cur.execute("INSERT INTO menu VALUES(173,'plain tea',20,'hotbeverage','v')")
cur.execute("INSERT INTO menu VALUES(174,'masala chai',25,'hotbeverage','v')")
cur.execute("INSERT INTO menu VALUES(175,'ginger chai',25,'hotbeverage','v')")
cur.execute("INSERT INTO menu VALUES(176,'cardamom chai',25,'hotbeverage','v')")
cur.execute("INSERT INTO menu VALUES(177,'green tea',35,'hotbeverage','v')")
cur.execute("INSERT INTO menu VALUES(178,'lemon tea',30,'hotbeverage','v')")
cur.execute("INSERT INTO menu VALUES(179,'herbal tea',40,'hotbeverage','v')")
cur.execute("INSERT INTO menu VALUES(180,'hot chocolate',80,'hotbeverage','v')")


# 11) COLD BEVERAGES (variety = 'cooldrink')
cur.execute("INSERT INTO menu VALUES(181,'fresh lime soda',60,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(182,'sweet lime juice',65,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(183,'salted lassi',55,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(184,'sweet lassi',60,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(185,'mint lassi',65,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(186,'rose milk',55,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(187,'buttermilk',30,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(188,'jal jeera',40,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(189,'mango juice',70,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(190,'orange juice',70,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(191,'watermelon juice',65,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(192,'pineapple juice',70,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(193,'apple juice',75,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(194,'cold coffee',90,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(195,'lemon iced tea',70,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(196,'peach iced tea',75,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(197,'sparkling water',40,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(198,'soda (sweet)',35,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(199,'soda (salt)',35,'cooldrink','v')")
cur.execute("INSERT INTO menu VALUES(200,'packaged water',20,'cooldrink','v')")


# 12) SIDE DISHES (variety = 'sidedish')
cur.execute("INSERT INTO menu VALUES(201,'egg omlette',20,'sidedish','nv')")
cur.execute("INSERT INTO menu VALUES(202,'egg kalaki',25,'sidedish','nv')")
cur.execute("INSERT INTO menu VALUES(203,'half boil egg',20,'sidedish','nv')")
cur.execute("INSERT INTO menu VALUES(204,'boiled egg (2 pcs)',25,'sidedish','nv')")
cur.execute("INSERT INTO menu VALUES(205,'egg podimas',40,'sidedish','nv')")
cur.execute("INSERT INTO menu VALUES(206,'plain papad',20,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(207,'roasted papad',25,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(208,'masala papad',35,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(209,'french fries',70,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(210,'peri peri fries',80,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(211,'potato wedges',75,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(212,'cheesy fries',90,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(213,'onion rings',65,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(214,'garlic bread',70,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(215,'cheese garlic bread',85,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(216,'veg salad',60,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(217,'green salad',55,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(218,'onion raita',40,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(219,'mixed veg raita',45,'sidedish','v')")
cur.execute("INSERT INTO menu VALUES(220,'pickle plate',25,'sidedish','v')")


con.commit()
con.close()
